# Generated by Django 4.0.3 on 2022-06-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_review_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='review_user',
        ),
    ]
