# Generated by Django 4.0.3 on 2022-05-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button_link',
            field=models.URLField(default='https://www.razorpay.com', max_length=255),
        ),
    ]
